name: .NET Build & Test

on:
  push:
    branches: [ "main", "develop" ]  # Triggers on pushes to these branches
  pull_request:
    branches: [ "main", "develop" ]  # Triggers on PRs targeting these branches

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup .NET 8 SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore, build, and test
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Optional: Publish artifacts (for deployment)
      - name: Publish
        run: dotnet publish -c Release -o ./publish
        if: github.ref == 'refs/heads/main'  # Only publish from 'main'